version: '3.9'

services:
  stock_parts_db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$DEV_POSTGRES_PASSWORD
      - POSTGRES_USER=$DEV_POSTGRES_USER
      - POSTGRES_DB=$DEV_POSTGRES_DB